# """Cascade service.

# Bridge between Phase 3's `ai.cascade.generate_cascade()` and the existing
# Reminder table. When an event_instance is created, this service generates
# the child reminders and inserts them with parent_event_instance_id set.
# """
# from __future__ import annotations

# from datetime import date as _date
# from typing import Optional

# from ..extensions import db
# from ..models import Reminder, EventInstance, Person
# from ..ai.cascade import generate_cascade, SUPPORTED_EVENT_TYPES


# # How many years of yearly reminders to generate per event type.
# # Picked to be reasonable defaults — Phase 5 frontend will let users override.
# _DEFAULT_YEARS = {
#     "birth":   80,   # cover a long lifespan
#     "wedding": 50,
#     "death":   30,
# }


# def fire_cascade_for_event(event_instance_id: int, user_id: int) -> int:
#     """Generate + persist cascade reminders for an event_instance.

#     Returns count of reminders inserted. Returns 0 silently for unsupported
#     event types (anniversary, other) — those don't cascade by design.
#     """
#     ev = EventInstance.query.filter_by(event_instance_id=event_instance_id,
#                                        user_id=user_id, is_active=True).first()
#     if not ev:
#         return 0
#     if ev.event_type not in SUPPORTED_EVENT_TYPES:
#         return 0

#     # Resolve subject name from subject_person_id if present
#     subject_name = ""
#     if ev.subject_person_id:
#         p = Person.query.filter_by(person_id=ev.subject_person_id,
#                                    user_id=user_id).first()
#         if p:
#             subject_name = p.name

#     years = _DEFAULT_YEARS.get(ev.event_type, 30)
#     children = generate_cascade(
#         event_type=ev.event_type,
#         event_date=ev.event_date,
#         subject_name=subject_name or ev.title,
#         years_to_generate=years,
#     )

#     inserted = 0
#     for child in children:
#         r = Reminder(
#             user_id=user_id,
#             title=child.title,
#             description=child.description,
#             reminder_datetime=child.reminder_datetime,
#             end_date=child.end_date,
#             repeat_type=child.repeat_type,
#             parent_event_instance_id=event_instance_id,
#             person_id=ev.subject_person_id,
#             is_auto_generated=True,
#             input_source="cascade",
#             is_active=True,
#         )
#         db.session.add(r)
#         inserted += 1

#     db.session.commit()
#     return inserted


# def list_cascade_for_event(event_instance_id: int, user_id: int) -> list[Reminder]:
#     """Return all reminders generated by a given event's cascade."""
#     return (Reminder.query
#             .filter_by(parent_event_instance_id=event_instance_id,
#                        user_id=user_id, is_active=True)
#             .order_by(Reminder.reminder_datetime).all())
"""Cascade service.

Bridge between Phase 3's `ai.cascade.generate_cascade()` and the existing
Reminder table. When an event_instance is created, this service generates
the child reminders and inserts them with parent_event_instance_id set.
"""
from __future__ import annotations

from datetime import date as _date
from typing import Optional

from ..extensions import db
from ..models import Reminder, EventInstance, Person
from ..ai.cascade import generate_cascade, SUPPORTED_EVENT_TYPES


# How many years of yearly reminders to generate per event type.
# Picked to be reasonable defaults — Phase 5 frontend will let users override.
_DEFAULT_YEARS = {
    "birth":   80,   # cover a long lifespan
    "wedding": 50,
    "death":   30,
}


def fire_cascade_for_event(event_instance_id: int, user_id: int) -> int:
    """Generate + persist cascade reminders for an event_instance.

    Returns count of reminders inserted. Returns 0 silently for unsupported
    event types (anniversary, other) — those don't cascade by design.
    """
    ev = EventInstance.query.filter_by(event_instance_id=event_instance_id,
                                       user_id=user_id, is_active=True).first()
    if not ev:
        return 0
    if ev.event_type not in SUPPORTED_EVENT_TYPES:
        return 0

    # Resolve subject name from subject_person_id if present
    subject_name = ""
    if ev.subject_person_id:
        p = Person.query.filter_by(person_id=ev.subject_person_id,
                                   user_id=user_id).first()
        if p:
            subject_name = p.name

    years = _DEFAULT_YEARS.get(ev.event_type, 30)
    children = generate_cascade(
        event_type=ev.event_type,
        event_date=ev.event_date,
        subject_name=subject_name or ev.title,
        years_to_generate=years,
    )

    inserted = 0
    for child in children:
        r = Reminder(
            user_id=user_id,
            title=child.title,
            description=child.description,
            reminder_datetime=child.reminder_datetime,
            end_date=child.end_date,
            repeat_type=child.repeat_type,
            parent_event_instance_id=event_instance_id,
            person_id=ev.subject_person_id,
            is_auto_generated=True,
            input_source="manual",   # cascade-spawned; constraint allows voice|manual only
            is_active=True,
        )
        db.session.add(r)
        inserted += 1

    db.session.commit()
    return inserted


def list_cascade_for_event(event_instance_id: int, user_id: int) -> list[Reminder]:
    """Return all reminders generated by a given event's cascade."""
    return (Reminder.query
            .filter_by(parent_event_instance_id=event_instance_id,
                       user_id=user_id, is_active=True)
            .order_by(Reminder.reminder_datetime).all())
